### PR TITLE
Adding error message to `differentialTest` when all models fail to converge

### PR DESCRIPTION
**Pull request by svteichman**
which passes the user an error message from one run of `bbdml`. Additionally updating the `setup-r` version from `v1` to `v2` for github actions and test coverage checks.

### CODE REVIEW

**Comment by svteichman** [comment]
@MariaAVC I'm not able to assign this pull request directly for you to review, but are you able to self-assign?

**Comment by bryandmartin** [comment]
Does this throw an error if the user doesn’t define `try_only`? Might want to add a catch, or just define it as the full list of taxa if `is.null` returns TRUE

**Comment by MariaAVC** [comment]
@svteichman It seems I do not have the write access to do a merge pull request.

**Comment by svteichman** [comment]
@adw96 could you give @MariaAVC permissions to do a pull request review please?

**Comment by adw96** [comment]
@svteichman 🙏 
@MariaAVC did that work?

**Comment by MariaAVC** [comment]
@adw96 Yes, it seems it worked! 👍

**Pull request merged**
